// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "QI Test - Descubra Seu Nível de Inteligência",
  description: "Teste científico de QI com 25 questões de lógica, padrões e raciocínio. Descubra sua pontuação de inteligência e perfil cognitivo em apenas 3 minutos.",
  keywords: "teste de qi, inteligência, raciocínio lógico, teste mental, avaliação cognitiva",
  authors: [{ name: "QI Test" }],
  openGraph: {
    title: "QI Test - Descubra Seu Nível de Inteligência",
    description: "Teste científico de QI com 25 questões. Descubra sua pontuação em 3 minutos.",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "QI Test - Descubra Seu Nível de Inteligência",
    description: "Teste científico de QI com 25 questões. Descubra sua pontuação em 3 minutos.",
  },
  viewport: "width=device-width, initial-scale=1",
  robots: "index, follow",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}